spring:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN

fr-datasource:
  type: com.dianping.zebra.group.jdbc.GroupDataSource
    zebra:
      jdbcRef: fr_f_fee_product

mybatis:
  type-aliases-package: com.flightroutes.flight.fee.bean
  mapper-locations: classpath:mybatis/mappers/*.xml

mapper:
  #  mappers:
  #    - com.flightroutes.flight.vcc.mapper.TestMapper
  not-empty: false
  identity: MYSQL

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  port: 8080


dubbo:
  protocol:
    name: dubbo
    port: 8444
  registry:
    address: 10.32.186.172:2180,10.21.148.9:2180,10.4.221.31:2180
    group: fr_f_fee
    id: fr_f_fee
    protocol: zookeeper
  application:
    name: fr_f_fee
    owner: chensj
    organization: frdubbo


  fee:
   group : fr_f_fee
  privilege:
    group: fr_f_privilege
  sso:
    group: fr_f_sso

